"""empty message

Revision ID: d1772be7d719
Revises: 5f1d54849c1e
Create Date: 2025-08-06 10:36:46.830648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1772be7d719'
down_revision = '5f1d54849c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('eyes',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eyes',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
